#!/usr/bin/env bash
# DESC control 16 — dependency scanning (CLAUDE.md §11.1, §11.3).
# Scans the frontend and backend npm dependencies and the AI service's Python
# requirements for known vulnerabilities, and files dated reports under
# documentation/security-compliance/dependency-scan-reports/<date>/.
# Needs network access to the advisory databases at BUILD time only — the
# running system makes no such calls.
#
# Exit code is non-zero when any HIGH or CRITICAL issue is found, so a build
# pipeline can stop on it.
set -u
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATE="$(date +%Y-%m-%d)"
OUT="$REPO_ROOT/documentation/security-compliance/dependency-scan-reports/$DATE"
mkdir -p "$OUT"
PIP_AUDIT="${PIP_AUDIT:-$(command -v pip-audit || echo "$HOME/.local/bin/pip-audit")}"
status=0

for app in frontend backend; do
  (cd "$REPO_ROOT/$app" && npm audit --json > "$OUT/$app-npm-audit.json" 2>/dev/null)
  (cd "$REPO_ROOT/$app" && npm audit --omit=dev --json > "$OUT/$app-npm-audit-runtime-only.json" 2>/dev/null)
done
"$PIP_AUDIT" -r "$REPO_ROOT/ai-service/requirements.txt" --format json > "$OUT/ai-service-pip-audit.json" 2> "$OUT/ai-service-pip-audit.log"

python3 - "$OUT" "$DATE" <<'PY' || status=1
import json, sys, pathlib
out, date = pathlib.Path(sys.argv[1]), sys.argv[2]
lines = [f"# Dependency scan — {date}", "", "Generated by `scripts/run-dependency-scan.sh` (DESC control 16).", "",
         "| Component | Scope | Critical | High | Moderate | Low |", "|---|---|---:|---:|---:|---:|"]
blocking = 0
for app in ("frontend", "backend"):
    for scope, name in (("all", f"{app}-npm-audit.json"), ("runtime only", f"{app}-npm-audit-runtime-only.json")):
        meta = json.loads((out / name).read_text() or "{}").get("metadata", {}).get("vulnerabilities", {})
        lines.append(f"| {app} (npm) | {scope} | {meta.get('critical',0)} | {meta.get('high',0)} | {meta.get('moderate',0)} | {meta.get('low',0)} |")
        if scope == "runtime only":
            blocking += meta.get("critical", 0) + meta.get("high", 0)
pip = json.loads((out / "ai-service-pip-audit.json").read_text() or "{}")
# pip-audit lists a package once per requirement that pulls it in; keep one row per advisory.
pip_vulns = sorted({(d["name"], d["version"], v["id"], ", ".join(v.get("fix_versions", [])) or "none yet")
                    for d in pip.get("dependencies", []) for v in d.get("vulns", [])})
lines.append(f"| ai-service (pip) | requirements.txt | {len(pip_vulns)} known (pip-audit does not grade severity) | | | |")
if pip_vulns:
    lines += ["", "## Python advisories", "", "| Package | Version | Advisory | Fixed in |", "|---|---|---|---|"]
    lines += [f"| {n} | {v} | {i} | {f} |" for n, v, i, f in pip_vulns]
lines += ["", "Raw JSON for each scan sits next to this file. \"Runtime only\" excludes build and test tools (`npm audit --omit=dev`) — those never ship to the server."]
(out / "summary.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
sys.exit(1 if blocking or pip_vulns else 0)
PY
exit $status
